name: cou_toolkit
version: 0.1.0
description: A polymer library of components for use with CoU applications

dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  polymer: ">=0.16.1+4 <0.17.0"
  paper_elements: ">=0.7.1 <0.8.0"
  dnd: ">=0.3.0 <0.4.0"

transformers:
- polymer:
    entry_points: web/index.html